[package]
edition = "2021"
name = "numstr"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.12", features = ["derive"]}
sscanf = "0.2.1"
clipboard = "0.5.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
gtk4 = "0.4.7"
